# Sir Qasim Assignment: Apply Numpy 20 Universal functions 

In [1]:
import numpy as np;

In [5]:
# 1
arr = np.arange(3*3*3)

In [6]:
# 2
arr.reshape(3, 3, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [7]:
# 3
arr.shape

(27,)

In [8]:
# 4
arr.size

27

In [9]:
# 5
arr.ndim

1

In [12]:
# 6
a = np.arange(25).reshape(5,5)
b = np.arange(25, 50).reshape(5,5)

a.dot(b)

array([[ 400,  410,  420,  430,  440],
       [1275, 1310, 1345, 1380, 1415],
       [2150, 2210, 2270, 2330, 2390],
       [3025, 3110, 3195, 3280, 3365],
       [3900, 4010, 4120, 4230, 4340]])

In [13]:
# 7
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
# 8
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
# 9
np.empty(5)

array([1., 1., 1., 1., 1.])

In [18]:
# 10
np.linspace(1,5,6)

array([1. , 1.8, 2.6, 3.4, 4.2, 5. ])

In [19]:
# 11
np.sort(a)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
# 12
np.argmax(a)

24

In [21]:
# 13
np.argmin(b)

0

In [22]:
# 14
np.argsort(a)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]], dtype=int64)

In [33]:
# 15
np.concatenate((a, b))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [34]:
# 16
np.stack(a)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [35]:
# 17
np.hstack(b)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [36]:
# 18
np.vstack(a)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [39]:
# 19
np.split(a,1)

[array([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])]

In [40]:
# 20
np.vsplit(b,1)

[array([[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]])]